# Import the required library

In [1]:
import numpy as np

# define the sigmoid function

In [2]:
def sigmoid(x):
    """Return the sigmoid of the x"""
    return (2 / (1 + np.exp(-x))) - 1

# Implement the Single Layer Perceptron

In [81]:
class Perceptron:
    def __init__(self, n_features, learning_rate=0.01, n_iteration=1000):
        """
        initialize the perceptron

        Parameters:
        ----------
            n_features: int
                Number of features of the input data
            learning_rate: float
                Learning rate of the perceptron
            n_iteration: int
                number of iteration to train the perceptron
            weight: numpy array
                Weight of the perceptron with shape (n_features + 1, 1)
                it includes the bias term
            dw: numpy array
                The gradient of the weight
        ----------
        """
        self.n_features = n_features
        self.weight = np.random.normal(size=(n_features + 1, 1))
        self.learning_rate = learning_rate
        self.n_iteration = n_iteration
        self.dw = 0

    def sigmoid(self, x):
        """Return the sigmoid of the x"""
        return (2 / (1 + np.exp(-x))) - 1

    def forward(self, x):
        """
        Return the output of the perceptron with input x and weight w
        """
        return self.sigmoid(np.dot(self.weight.T, x))

    def grad(self, x, y):
        """
        Compute the gradient of the weight

        Parameters:
        ----------
            x: numpy array
                input of the perceptron with shape (n_features + 1, 1)
                it includes the bias term
            y: numpy array
                target of the perceptron with shape (1, 1)

        """
        output = self.forward(x)
        self.dw = np.sum(-0.5*(y - output)*(1 - output**2)*x, 1, keepdims=2)
        return self.dw

    def step(self):
        """
        Update the weight of the perceptron with the gradient
        """
        self.weight = self.weight - self.learning_rate*self.dw
        return self.weight

    def train(self, x, y):
        """Train the perceptron"""
        for _ in range(self.n_iteration):
            self.grad(x, y)
            self.step()

    def predict(self, x):
        """Return the prediction of the perceptron"""
        return self.forward(x)

# Create the data for the XOR problem

In [82]:
x_xor = np.array([[1, 1, 0, 0], [1, 0, 1, 0], [1, 1, 1, 1]])
y_xor = np.array([[0, 1, 1, 0]])

x_and = np.array([[1, 1, 0, 0], [1, 0, 1, 0], [1, 1, 1, 1]])
y_and = np.array([[1, 0, 0, 0]])

x_or = np.array([[1, 1, 0, 0], [1, 0, 1, 0], [1, 1, 1, 1]])
y_or = np.array([[1, 1, 1, 0]])

# Train the model

In [83]:
model_xor = Perceptron(2)
model_xor.train(x_xor, y_xor)

model_and = Perceptron(2)
model_and.train(x_and, y_and)

model_or = Perceptron(2)
model_or.train(x_or, y_or)

In [84]:
print("XOR")
print(f"The weight of the perceptron is\n {model_xor.weight}")
print(f"The output of the perceptron is\n {model_xor.predict(x_xor)}")

print("\nAND")
print(f"The weight of the perceptron is\n {model_and.weight}")
print(f"The output of the perceptron is\n {model_and.predict(x_and)}")

print("\nOR")
print(f"The weight of the perceptron is\n {model_or.weight}")
print(f"The output of the perceptron is\n {model_or.predict(x_or)}")

XOR
The weight of the perceptron is
 [[0.47030654]
 [0.64859301]
 [0.65865505]]
The output of the perceptron is
 [[0.71078929 0.51129442 0.57410459 0.3179164 ]]

AND
The weight of the perceptron is
 [[ 0.68164496]
 [ 0.76183919]
 [-0.1926269 ]]
The output of the perceptron is
 [[ 0.55489644  0.23975017  0.27716279 -0.09601674]]

OR
The weight of the perceptron is
 [[1.57234997]
 [1.06668253]
 [0.7290669 ]]
The output of the perceptron is
 [[0.9333851  0.81798863 0.71526146 0.34920095]]
