# Import the required library

In [1]:
import numpy as np

# define the sigmoid function

In [2]:
def sigmoid(x):
    """Return the sigmoid of the x"""
    return (2 / (1 + np.exp(-x))) - 1

# Implement the Single Layer Perceptron

In [3]:
class Perceptron:
    def __init__(self, n_features, learning_rate=0.01, n_iteration=1000):
        """
        initialize the perceptron

        Parameters:
        ----------
            n_features: int
                Number of features of the input data
            learning_rate: float
                Learning rate of the perceptron
            n_iteration: int
                number of iteration to train the perceptron
            weight: numpy array
                Weight of the perceptron with shape (n_features + 1, 1)
                it includes the bias term
            dw: numpy array
                The gradient of the weight
        ----------
        """
        self.n_features = n_features
        self.weight = np.random.normal(size=(n_features + 1, 1))
        self.learning_rate = learning_rate
        self.n_iteration = n_iteration
        self.dw = 0

    def sigmoid(self, x):
        """Return the sigmoid of the x"""
        return (2 / (1 + np.exp(-x))) - 1

    def forward(self, x):
        """
        Return the output of the perceptron with input x and weight w
        """
        return self.sigmoid(np.dot(self.weight.T, x))

    def grad(self, x, y):
        """
        Compute the gradient of the weight

        Parameters:
        ----------
            x: numpy array
                input of the perceptron with shape (n_features + 1, 1)
                it includes the bias term
            y: numpy array
                target of the perceptron with shape (1, 1)

        """
        output = self.forward(x)
        self.dw = np.sum(-0.5*(y - output)*(1 - output**2)*x, 1, keepdims=2)
        return self.dw

    def step(self):
        """
        Update the weight of the perceptron with the gradient
        """
        self.weight = self.weight - self.learning_rate*self.dw
        return self.weight

    def train(self, x, y):
        """Train the perceptron"""
        for _ in range(self.n_iteration):
            self.grad(x, y)
            self.step()

    def predict(self, x):
        """Return the prediction of the perceptron"""
        return self.forward(x)

# Create the data for the XOR problem

In [4]:
x_xor = np.array([[1, 1, 0, 0], [1, 0, 1, 0], [1, 1, 1, 1]])
y_xor = np.array([[0, 1, 1, 0]])

x_and = np.array([[1, 1, 0, 0], [1, 0, 1, 0], [1, 1, 1, 1]])
y_and = np.array([[1, 0, 0, 0]])

x_or = np.array([[1, 1, 0, 0], [1, 0, 1, 0], [1, 1, 1, 1]])
y_or = np.array([[1, 1, 1, 0]])

# Train the model

In [6]:
model_xor = Perceptron(n_features=2, learning_rate=0.01, n_iteration=1000)
model_xor.train(x_xor, y_xor)

model_and = Perceptron(n_features=2, learning_rate=0.01, n_iteration=1000)
model_and.train(x_and, y_and)

model_or = Perceptron(n_features=2, learning_rate=0.01, n_iteration=1000)
model_or.train(x_or, y_or)

In [7]:
print("XOR")
print(f"The weight of the perceptron is\n {model_xor.weight}")
print(f"The output of the perceptron is\n {(model_xor.predict(x_xor) > 0.5).astype(int)}")

print("\nAND")
print(f"The weight of the perceptron is\n {model_and.weight}")
print(f"The output of the perceptron is\n {(model_and.predict(x_and) > 0.5).astype(int)}")

print("\nOR")
print(f"The weight of the perceptron is\n {model_or.weight}")
print(f"The output of the perceptron is\n {(model_or.predict(x_or) > 0.5).astype(int)}")

XOR
The weight of the perceptron is
 [[1.24516128]
 [1.11676586]
 [0.4157379 ]]
The output of the perceptron is
 [[1 1 1 0]]

AND
The weight of the perceptron is
 [[ 0.66048634]
 [ 0.81937755]
 [-0.21200441]]
The output of the perceptron is
 [[1 0 0 0]]

OR
The weight of the perceptron is
 [[1.46801495]
 [2.21010857]
 [0.41109937]]
The output of the perceptron is
 [[1 1 1 0]]
